CREATE TABLE employee (
id BIGINT PRIMARY KEY AUTO_INCREMENT,first_name VARCHAR(50),last_name VARCHAR(50),email VARCHAR(100),department VARCHAR(50),salary DOUBLE
);
CREATE TABLE users (
id BIGINT PRIMARY KEY AUTO_INCREMENT,username VARCHAR(50) UNIQUE,password VARCHAR(255),role VARCHAR(20)
);
